import { Card, CardType } from '@/shared/models/card';

export const SUPPORTED_OPENCLAW_CARD_TYPES = [
  CardType.JOB_SEEKING,
  CardType.RECRUITMENT,
] as const;

export const OPENCLAW_FORBIDDEN_SERVER_FIELDS = [
  'card_id',
  'openclaw_id',
  'status',
  'created_at',
  'updated_at',
] as const;

export type OpenclawPublishErrorReason =
  | 'required'
  | 'invalid_type'
  | 'invalid_value'
  | 'invalid_format'
  | 'forbidden_field'
  | 'invalid_auth';

export interface OpenclawPublishError {
  field: string;
  reason: OpenclawPublishErrorReason;
  guidance: string;
}

type OpenclawPublishEnvelope = {
  cardType: CardType;
  payload: Record<string, unknown>;
};

type OpenclawPublishValidationResult =
  | { ok: true; data: OpenclawPublishEnvelope }
  | { ok: false; errors: OpenclawPublishError[] };

const allowedTopLevelFields = new Set(['card_type', 'payload']);
const forbiddenServerFields = new Set<string>(OPENCLAW_FORBIDDEN_SERVER_FIELDS);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

function invalidTopLevelFieldError(field: string): OpenclawPublishError {
  return {
    field,
    reason: 'invalid_format',
    guidance:
      'Only send `card_type` and `payload` at the top level. Move any business fields into `payload` and send the request again.',
  };
}

function forbiddenFieldGuidance(field: string): string {
  switch (field) {
    case 'card_id':
      return 'Remove `card_id` from the request. This value is generated by Openthedoor after the publish request is accepted.';
    case 'openclaw_id':
      return 'Remove `openclaw_id` from the request. Openthedoor derives this value from the authenticated publish key.';
    case 'status':
      return 'Remove `status` from the request. Openthedoor sets card status on the server after the publish request succeeds.';
    case 'created_at':
    case 'updated_at':
      return `Remove \`${field}\` from the request. Openthedoor sets timestamps on the server after the publish request succeeds.`;
    default:
      return `Remove \`${field}\` from the request. This field is owned by Openthedoor and must not be supplied by the client.`;
  }
}

function forbiddenFieldError(
  fieldPath: string,
  fieldName: string
): OpenclawPublishError {
  return {
    field: fieldPath,
    reason: 'forbidden_field',
    guidance: forbiddenFieldGuidance(fieldName),
  };
}

export function parseOpenclawPublishBearerToken(
  authorizationHeader: string | null
): string | null {
  if (!authorizationHeader) {
    return null;
  }

  const match = authorizationHeader.match(/^Bearer\s+(.+)$/i);
  const token = match?.[1]?.trim();

  return token || null;
}

export function createInvalidAuthResponse(): Response {
  return Response.json(
    {
      code: -1,
      message: 'invalid auth',
      errors: [
        {
          field: 'authorization',
          reason: 'invalid_auth',
          guidance:
            'Send `Authorization: Bearer <api_key>` with a valid Openclaw publish key. If you do not have one, ask the operator for a fresh key and do not guess.',
        },
      ],
    },
    { status: 401 }
  );
}

export function createValidationErrorResponse(
  errors: OpenclawPublishError[]
): Response {
  return Response.json(
    {
      code: -1,
      message: 'validation failed',
      errors,
    },
    { status: 400 }
  );
}

export function createInvalidJsonResponse(): Response {
  return createValidationErrorResponse([
    {
      field: 'body',
      reason: 'invalid_format',
      guidance:
        'Send a valid JSON object with `card_type` and `payload`. If the user gave you raw text or a document summary, ask follow-up questions and convert it into named fields before sending the request.',
    },
  ]);
}

export function createPublishSuccessResponse(card: Card): Response {
  return Response.json({
    code: 0,
    message: 'ok',
    data: {
      card_id: card.cardId,
      card_type: card.cardType,
      status: card.status,
      created_at: card.createdAt.toISOString(),
      updated_at: card.updatedAt.toISOString(),
    },
  });
}

export function createPublishFailureResponse(): Response {
  return Response.json(
    {
      code: -1,
      message: 'publish failed',
    },
    { status: 500 }
  );
}

export function validateOpenclawPublishEnvelope(
  input: unknown
): OpenclawPublishValidationResult {
  if (!isPlainObject(input)) {
    return {
      ok: false,
      errors: [
        {
          field: 'body',
          reason: 'invalid_format',
          guidance:
            'Send a JSON object with `card_type` and `payload`. If the user has only raw notes, ask follow-up questions and structure them into named fields before sending the request.',
        },
      ],
    };
  }

  const errors: OpenclawPublishError[] = [];
  const body = input as Record<string, unknown>;

  if (!('card_type' in body)) {
    errors.push({
      field: 'card_type',
      reason: 'required',
      guidance:
        'Add `card_type` and set it to either `job_seeking` or `recruitment`. Ask the user which card type applies if it is unclear, and do not guess.',
    });
  } else if (typeof body.card_type !== 'string') {
    errors.push({
      field: 'card_type',
      reason: 'invalid_type',
      guidance:
        'Set `card_type` to a string value of either `job_seeking` or `recruitment`, then send the request again.',
    });
  } else if (
    !SUPPORTED_OPENCLAW_CARD_TYPES.includes(body.card_type as CardType)
  ) {
    errors.push({
      field: 'card_type',
      reason: 'invalid_value',
      guidance:
        'Set `card_type` to either `job_seeking` or `recruitment`, then send the request again. Do not invent a new card type.',
    });
  }

  if (!('payload' in body)) {
    errors.push({
      field: 'payload',
      reason: 'required',
      guidance:
        'Add `payload` as a JSON object containing the user-provided card details. Ask the user for any missing details instead of guessing.',
    });
  } else if (!isPlainObject(body.payload)) {
    errors.push({
      field: 'payload',
      reason: 'invalid_type',
      guidance:
        'Set `payload` to a JSON object. If the user gave you a list or plain text, ask follow-up questions and convert it into named fields instead of guessing.',
    });
  } else {
    for (const key of Object.keys(body.payload)) {
      if (forbiddenServerFields.has(key)) {
        errors.push(forbiddenFieldError(`payload.${key}`, key));
      }
    }
  }

  for (const key of Object.keys(body)) {
    if (allowedTopLevelFields.has(key)) {
      continue;
    }

    if (forbiddenServerFields.has(key)) {
      errors.push(forbiddenFieldError(key, key));
      continue;
    }

    errors.push(invalidTopLevelFieldError(key));
  }

  if (errors.length > 0) {
    return {
      ok: false,
      errors,
    };
  }

  return {
    ok: true,
    data: {
      cardType: body.card_type as CardType,
      payload: body.payload as Record<string, unknown>,
    },
  };
}
