import { describe, expect, it } from 'vitest';

import {
  createInvalidAuthResponse,
  createValidationErrorResponse,
  validateOpenclawPublishEnvelope,
} from './openclaw-publish';

describe('openclaw publish validation', () => {
  it('accepts the minimal supported publish envelope', () => {
    const result = validateOpenclawPublishEnvelope({
      card_type: 'job_seeking',
      payload: {
        candidate_profile: 'backend engineer',
      },
    });

    expect(result).toEqual({
      ok: true,
      data: {
        cardType: 'job_seeking',
        payload: {
          candidate_profile: 'backend engineer',
        },
      },
    });
  });

  it('returns structured validation errors for missing and forbidden fields', () => {
    const result = validateOpenclawPublishEnvelope({
      payload: {
        card_id: 'card_123',
      },
      unexpected: true,
    });

    expect(result.ok).toBe(false);
    expect(result.errors).toEqual([
      {
        field: 'card_type',
        reason: 'required',
        guidance:
          'Add `card_type` and set it to either `job_seeking` or `recruitment`. Ask the user which card type applies if it is unclear, and do not guess.',
      },
      {
        field: 'payload.card_id',
        reason: 'forbidden_field',
        guidance:
          'Remove `card_id` from the request. This value is generated by Openthedoor after the publish request is accepted.',
      },
      {
        field: 'unexpected',
        reason: 'invalid_format',
        guidance:
          'Only send `card_type` and `payload` at the top level. Move any business fields into `payload` and send the request again.',
      },
    ]);
  });

  it('rejects payload values that are not JSON objects', () => {
    const result = validateOpenclawPublishEnvelope({
      card_type: 'recruitment',
      payload: ['not', 'an', 'object'],
    });

    expect(result).toEqual({
      ok: false,
      errors: [
        {
          field: 'payload',
          reason: 'invalid_type',
          guidance:
            'Set `payload` to a JSON object. If the user gave you a list or plain text, ask follow-up questions and convert it into named fields instead of guessing.',
        },
      ],
    });
  });
});

describe('openclaw publish response helpers', () => {
  it('returns a structured invalid auth response', async () => {
    const response = createInvalidAuthResponse();

    expect(response.status).toBe(401);
    await expect(response.json()).resolves.toEqual({
      code: -1,
      message: 'invalid auth',
      errors: [
        {
          field: 'authorization',
          reason: 'invalid_auth',
          guidance:
            'Send `Authorization: Bearer <api_key>` with a valid Openclaw publish key. If you do not have one, ask the operator for a fresh key and do not guess.',
        },
      ],
    });
  });

  it('returns a structured validation error response', async () => {
    const response = createValidationErrorResponse([
      {
        field: 'card_type',
        reason: 'invalid_value',
        guidance:
          'Set `card_type` to either `job_seeking` or `recruitment`, then send the request again. Do not invent a new card type.',
      },
    ]);

    expect(response.status).toBe(400);
    await expect(response.json()).resolves.toEqual({
      code: -1,
      message: 'validation failed',
      errors: [
        {
          field: 'card_type',
          reason: 'invalid_value',
          guidance:
            'Set `card_type` to either `job_seeking` or `recruitment`, then send the request again. Do not invent a new card type.',
        },
      ],
    });
  });
});
